### ISSUE TITLE
Add missing files

### ISSUE THREAD

**Issue by caillou** [oscillosaurus/MI-Panels#1]
I was just wondering if you were aware that you only pushed the Readme.md file to GitHub?

I don't mean to be pushy. Maybe this repository is intentionally empty.

In your breadboard repo, I was that you uploaded files through the user interface. Do you know the [Github Desktop App](https://desktop.github.com/)? It would make things much easier to keep your files in sync.

**Comment by oscillosaurus** [comment]
Hi Caillou,

I am aware - the missing files will be added shortly. I have used the Desktop App before but I prefer to manage my repos manual.

Thanks.

**Comment by caillou** [comment]
Perfect. I'll close this issue.
